services:
  minio:
    image: registry.docker.ir/minio/minio:latest
    ports:
      - "9000:9000" # api
      - "9001:9001" # ui
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  minio_data:
