[package]
name = "server"
version.workspace = true
edition.workspace = true

[dependencies]
routes = { path = "../routes" }
utils = { path = "../utils" }
tokio = { workspace = true }
actix-web = { workspace = true }
actix-cors = { workspace = true }
env_logger = { workspace = true }
